<a href="https://colab.research.google.com/github/Bhargavieluri123/Project/blob/main/Minor_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
!pip install ipython-autotime
%load_ext autotime

The autotime extension is already loaded. To reload it, use:
  %reload_ext autotime
time: 4.71 s (started: 2021-05-18 15:06:17 +00:00)


In [18]:
import os
import numpy as np

import matplotlib.pyplot as plt
from skimage.io import imread
from skimage.transform import resize
 
target = []
images=[]
flat_data = []

datadir ='/content/drive/MyDrive/python april/images'

categories = ['brinjal','carrot','potato']

for i in categories:
  class_num=categories.index(i)
  path = os.path.join(datadir,i)
  for img in os.listdir(path):
      img_array = imread(os.path.join(path,img))
      img_resized = resize(img_array,(150,150,3)) 
      flat_data.append(img_resized.flatten())
      images.append(img_resized)
      target.append(class_num)
flat_data = np.array(flat_data)
target = np.array(target)
images=np.array(images)

time: 55.1 s (started: 2021-05-18 15:06:22 +00:00)


In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
time: 4.2 ms (started: 2021-05-18 15:07:17 +00:00)


In [20]:
# Splitting the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,test_size=0.3,random_state=100)

time: 19.3 ms (started: 2021-05-18 15:07:17 +00:00)


In [5]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [{'C':[1,10,100,1000],'kernel':['linear']},
              {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']},]
svc=svm.SVC(probability=True)
clf=GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

time: 1min 44s (started: 2021-05-18 15:03:29 +00:00)


In [6]:
y_pred=clf.predict(x_test)
y_pred

array([0, 1, 0, 0, 1, 2, 0, 0, 2, 2, 2, 1, 0, 0, 1, 2, 0, 2, 1, 0, 2, 1,
       2, 0, 2])

time: 167 ms (started: 2021-05-18 15:05:14 +00:00)


In [7]:
y_test

array([0, 1, 0, 0, 1, 2, 0, 0, 0, 2, 2, 1, 1, 0, 1, 1, 0, 2, 1, 0, 2, 2,
       2, 0, 1])

time: 3.91 ms (started: 2021-05-18 15:05:14 +00:00)


In [8]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

time: 1.32 ms (started: 2021-05-18 15:05:14 +00:00)


In [9]:
accuracy_score(y_pred,y_test)

0.8

time: 4.61 ms (started: 2021-05-18 15:05:15 +00:00)


In [10]:
confusion_matrix(y_pred,y_test)

array([[9, 1, 0],
       [0, 5, 1],
       [1, 2, 6]])

time: 5.29 ms (started: 2021-05-18 15:05:15 +00:00)


In [11]:
import pickle
pickle.dump(clf,open('img_model.p','wb'))

time: 52.5 ms (started: 2021-05-18 15:05:15 +00:00)


In [12]:
model=pickle.load(open('img_model.p','rb'))

time: 21.4 ms (started: 2021-05-18 15:05:15 +00:00)


In [13]:
flat_data=[]
url = input('Enter your url')
img = imread(url)
img_resized=resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data=np.array(flat_data)
print(img.shape)
y_out=model.predict(flat_data)
y_out=categories[y_out[0]]
print(f'PREDICTED OUTPUT: {y_out}')


Enter your urlhttps://sc04.alicdn.com/kf/U6a1b0b5c46bd48e9b97283fb2e4e9879t/1013564064/U6a1b0b5c46bd48e9b97283fb2e4e9879t.jpg
(1200, 1200, 3)
PREDICTED OUTPUT: potato
time: 38.6 s (started: 2021-05-18 15:05:15 +00:00)


In [14]:
 !pip install streamlit --quiet
!pip install pyngrok==4.1.1 --quiet
from pyngrok import ngrok

     |████████████████████████████████| 8.2MB 5.1MB/s 
     |████████████████████████████████| 4.2MB 37.0MB/s 
     |████████████████████████████████| 81kB 8.1MB/s 
     |████████████████████████████████| 92kB 8.4MB/s 
     |████████████████████████████████| 174kB 53.8MB/s 
     |████████████████████████████████| 112kB 46.9MB/s 
     |████████████████████████████████| 122kB 45.1MB/s 
     |████████████████████████████████| 71kB 7.0MB/s 
ERROR: google-colab 1.0.0 has requirement ipykernel~=4.10, but you'll have ipykernel 5.5.5 which is incompatible.
time: 19.9 s (started: 2021-05-18 15:05:53 +00:00)


In [15]:
%%writefile App.py
import streamlit as st
import numpy as np
from skimage.io import imread
from skimage.transform import resize
import pickle
from PIL import Image
st.title('Image Classifier  using machine learning')
st.text('Upload the image ')
model=pickle.load(open('img_model.p','rb'))
uploaded_file=st.file_uploader("Choose an image....",type='jpg')
if uploaded_file is not None:
  img=Image.open(uploaded_file)
  st.image(img,caption='Uploaded Image')
  if st.button('PREDICT'):
    categories = ['brinjal','carrot','potato']
    st.write('Result.....')
    flat_data=[]
    img =np.array(img)
    img_resized=resize(img,(150,150,3))
    flat_data.append(img_resized.flatten())
    flat_data=np.array(flat_data)
    y_out=model.predict(flat_data)
    y_out=categories[y_out[0]]
    st.write(f'PREDICTED OUTPUT: {y_out}')

Writing App.py
time: 3.45 ms (started: 2021-05-18 15:06:13 +00:00)


In [16]:
!nohup streamlit run App.py &
url=ngrok.connect(port='8501')
url

nohup: appending output to 'nohup.out'


'http://65b9cf358b71.ngrok.io'

time: 2.33 s (started: 2021-05-18 15:06:13 +00:00)
